<?php
$z[0]=Array("field","",83,111);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",113,142);
$z[1][4]['name']="typename";
$z[2]=Array("field","",181,209);
$z[2][4]['name']="typeurl";
$z[3]=Array("arclist","\r\n            	<a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:fulltitle/]\" /></a>\r\n                <h4><a href=\"[field:arcurl /]\">[field:title /]</a></h4>\r\n                <p>[field:description function=\"cn_substr(@me,50)\"/]...</p>\r\n                ",298,627);
$z[3][4]['row']="1";
$z[3][4]['titlelen']="22";
$z[3][4]['type']="image.";
$z[4]=Array("arclist","\r\n                <li>·<a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n                ",696,840);
$z[4][4]['titlelen']="40";
$z[4][4]['row']="6";

?>