<!-- 图片 -->
			<li class="post">
            <span class="sc"><a href="#">喜欢</a></span>
            <span class="view"><a href="#"></a></span>
			<div class="link">
			<span class="img">
			[field:array runphp='yes']@me = (empty(@me['litpic']) ? "" : "<a href='{@me['arcurl']}' target='_blank'><img src='{@me['litpic']}'/></a>"); [/field:array]
			<span class="arr"><span></span></span>			</span>
			<span class="text">
			<em>
            <b><a href="[field:arcurl/]" class="title">[field:title/]</a></b>
			<p>
				[field:description/]... 
            </p>
			</em>
            <p class="info">
                <a href="#" class="view" title=" 访问">[field:click/]</a>
                <a href="#" class="good" title="好评">[field:scores/]</a>
             </p>
            </span>
            </div>
            </li>