<?php
$z[0]=Array("arcurl","",139,154);
$z[1]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' target='_blank'><img src='{@me['litpic']}'/></a>\"); ",218,372);
$z[1][4]['runphp']="yes";
$z[2]=Array("arcurl","",484,499);
$z[3]=Array("title","",515,529);
$z[4]=Array("description","",551,571);
$z[5]=Array("arcurl","",660,675);
$z[6]=Array("click","",706,720);
$z[7]=Array("scores","",782,797);

?>