<td>
            <div class="newprod_list">
				<div class="newprod_pic"><a href="[field:arcurl/]" title="[field:fulltitle/]"><img name="picautozoom" border="0" src="[field:litpic/]" class="prodthumb" /></a></div>
                <div class="newprod_name"><a href="[field:arcurl/]">[field:title/]</a></div>
                <div class="newprod_intr">分类: <a href="[field:typeurl/]">[field:typename /]</a></div>
                <div class="blankbar1"></div>
            </div>
			</td>