<?php
$z[0]=Array("global","",246,272);
$z[0][4]['name']="cfg_cmspath";
$z[1]=Array("global","",395,421);
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("global","",798,824);
$z[2][4]['name']="cfg_cmspath";
$z[3]=Array("global","",866,892);
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("global","",1043,1069);
$z[4][4]['name']="cfg_cmspath";
$z[5]=Array("global","",1385,1411);
$z[5][4]['name']="cfg_cmspath";
$z[6]=Array("global","",1585,1611);
$z[6][4]['name']="cfg_cmspath";
$z[7]=Array("global","",1692,1718);
$z[7][4]['name']="cfg_cmspath";
$z[8]=Array("global","",2010,2036);
$z[8][4]['name']="cfg_cmspath";
$z[9]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",2094,2337);
$z[9][4]['type']="top";
$z[9][4]['row']="10";
$z[9][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[10]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2566,2695);
$z[10][4]['row']="7";
$z[10][4]['getall']="1";
$z[10][4]['sort']="month";

?>