<?php
$z[0]=Array("global","",151,174);
$z[0][4]['name']="css_path";
$z[1]=Array("channelartlist"," \r\n         <li>\r\n        <span><A href=\"{dede:field name='typeurl'/}\" >{dede:field name='typename'/}</A>\r\n		<ul>\r\n        {dede:channel type='son' noself='yes'}<li><A href=\"[field:typeurl/]\">[field:typename/]</A></li>{/dede:channel}\r\n        </ul></span>\r\n        </li>\r\n",520,848);
$z[1][4]['typeid']="top";
$z[2]=Array("arclist","\r\nlinkarr[[field:global.autoindex/]] = \"[field:arcurl/]\";\r\npicarr[[field:global.autoindex/]]  = \"[field:litpic/]\";\r\ntextarr[[field:global.autoindex/]] = \"[field:title function='html2text(@me)'/]\";\r\n",1870,2126);
$z[2][4]['flag']="f";
$z[2][4]['row']="5";
$z[2][4]['typeid']="28";
$z[3]=Array("global","",2754,2780);
$z[3][4]['name']="cfg_cmspath";
$z[4]=Array("global","",2780,2803);
$z[4][4]['name']="css_path";
$z[5]=Array("global","",3199,3225);
$z[5][4]['name']="cfg_cmspath";
$z[6]=Array("global","",3225,3248);
$z[6][4]['name']="css_path";

?>