<?php
$z[0]=Array("global","",233,261);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",273,299);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",343,373);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",410,437);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("include","",536,571);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channelartlist","<div class=\"content2_sum\"> <h3>{dede:field.typename/}</h3> <ul>  {dede:arclist row='9' titlelen='60'}<li><a target=\"_blank\" href=\"[field:arcurl/]\">[field:title/]</a><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li>  {/dede:arclist}  </ul> </div>",601,912);
$z[5][4]['row']="";
$z[6]=Array("flink","",1213,1226);
$z[7]=Array("include","",1235,1272);
$z[7][4]['filename']="footer.htm";

?>