<?php
$z[0]=Array("global","",238,266);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",279,298);
$z[1][4]['name']="title";
$z[2]=Array("global","",299,325);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",366,395);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",435,493);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",590,625);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",708,730);
$z[6][4]['name']="typename";
$z[7]=Array("channel","   <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>  ",759,870);
$z[7][4]['row']="10";
$z[7][4]['type']="top";
$z[8]=Array("flink","",939,998);
$z[8][4]['linktype']="1";
$z[8][4]['row']="30";
$z[8][4]['type']="text";
$z[9]=Array("field","",1118,1147);
$z[9][4]['name']="position";
$z[10]=Array("list","<li><a target=\"_blank\" href=\"[field:arcurl/]\">[field:title/]</a> <span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span></li> ",1204,1372);
$z[10][4]['pagesize']="15";
$z[11]=Array("pagelist","",1423,1501);
$z[11][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[11][4]['listsize']="4";
$z[12]=Array("include","",1641,1678);
$z[12][4]['filename']="footer.htm";

?>