<?php
$z[0]=Array("field","",317,336);
$z[0][4]['name']="title";
$z[1]=Array("global","",337,363);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",404,433);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",473,531);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1040,1075);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n                      <li ><a href=\"[field:typeurl/]\" target=\"_self\">[field:typename/]</a></li>                     \r\n								 ",1420,1602);
$z[5][4]['type']="son";
$z[5][4]['typeid']="21";
$z[6]=Array("include","",1676,1711);
$z[6][4]['filename']="left.htm";
$z[7]=Array("field","",1815,1844);
$z[7][4]['name']="position";
$z[8]=Array("field","",1851,1874);
$z[8][4]['name']="seotitle";
$z[9]=Array("list","\r\n		<li><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n         ",1953,2118);
$z[9][4]['pagesize']="15";
$z[10]=Array("pagelist","",2198,2276);
$z[10][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",2354,2389);
$z[11][4]['filename']="foot.htm";

?>