<?php
$z[0]=Array("item","",4,77);
$z[0][4]['name']="ิดย๋ธ็";
$z[0][4]['link']="http://www.ymg.cc";
$z[0][4]['rank']="";
$z[0][4]['target']="_blank";
$z[1]=Array("item","",81,159);
$z[1][4]['name']="www.ymg.cc";
$z[1][4]['link']="http://www.ymg.cc/";
$z[1][4]['rank']="";
$z[1][4]['target']="_blank";
$z[2]=Array("item","",163,238);
$z[2][4]['name']="นูทฝยÛฬณ";
$z[2][4]['link']="http://www.ymg.cc";
$z[2][4]['rank']="";
$z[2][4]['target']="_blank";

?>