<?php
$z[0]=Array("global","",168,193);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",255,280);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",338,363);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",394,420);
$z[3][4]['name']="cfg_dataurl";
$z[4]=Array("global","",546,573);
$z[4][4]['name']="cfg_basehost";
$z[5]=Array("global","",642,669);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",672,698);
$z[6][4]['name']="cfg_webname";
$z[7]=Array("global","",853,880);
$z[7][4]['name']="cfg_basehost";
$z[8]=Array("global","",892,924);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",971,997);
$z[9][4]['name']="cfg_webname";
$z[10]=Array("myad","",1052,1087);
$z[10][4]['name']="innerTopBanner1";
$z[11]=Array("myad","",1122,1157);
$z[11][4]['name']="innerTopBanner2";
$z[12]=Array("global","",1439,1464);
$z[12][4]['name']="cfg_cmsurl";
$z[13]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",1502,1745);
$z[13][4]['type']="top";
$z[13][4]['row']="10";
$z[13][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[14]=Array("global","",1837,1862);
$z[14][4]['name']="cfg_cmsurl";
$z[15]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2639,2769);
$z[15][4]['row']="10";
$z[15][4]['getall']="1";
$z[15][4]['sort']="month";

?>