<?php
$z[0]=Array("field","",255,274);
$z[0][4]['name']="title";
$z[1]=Array("global","",275,303);
$z[1][4]['name']="cfg_indexname";
$z[2]=Array("field","",344,373);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",413,471);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",655,697);
$z[4][4]['filename']="head_92game.htm";
$z[5]=Array("field","",959,988);
$z[5][4]['name']="position";
$z[6]=Array("list","\r\n<li><a href=\"[field:arcurl/]\" class=\"img\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" /><i class=\"tit\">[field:title/]</i><s></s></a></li>\r\n",1281,1488);
$z[6][4]['pagesize']="20";
$z[6][4]['flag']="p";
$z[7]=Array("arclist","\r\n<li><a  href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span></li>\r\n",1830,2008);
$z[7][4]['row']="9";
$z[7][4]['typeid']="1";
$z[8]=Array("arclist","\r\n<li><a  href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a><span>[field:pubdate function=\"MyDate('m-d',@me)\"/]</span></li>\r\n",2264,2445);
$z[8][4]['row']="9";
$z[8][4]['orderby']="hot";
$z[9]=Array("pagelist","",2741,2812);
$z[9][4]['listitem']="index,end,pre,next,pageno,info";
$z[9][4]['listsize']="5";
$z[10]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" class=\"img\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" /><i class=\"tit\">[field:title/]</i><s></s></a></li>\r\n",3076,3303);
$z[10][4]['pagesize']="6";
$z[10][4]['flag']="p";
$z[10][4]['orderby']="rand";
$z[11]=Array("include","",3435,3479);
$z[11][4]['filename']="footer_92game.htm";

?>