<?php
$z[0]=Array("global","",255,310);
$z[0][4]['name']="keyword";
$z[0][4]['function']="RemoveXSS(@me)";
$z[1]=Array("global","",319,347);
$z[1][4]['name']="cfg_indexname";
$z[2]=Array("include","",535,577);
$z[2][4]['filename']="head_92game.htm";
$z[3]=Array("global","",730,785);
$z[3][4]['name']="keyword";
$z[3][4]['function']="RemoveXSS(@me)";
$z[4]=Array("list","\r\n<li><a href=\"[field:arcurl/]\" class=\"img\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\" /><i class=\"tit\"<font color='red'>[field:title/]</i><s></s></a></li>\r\n",918,1116);
$z[4][4]['perpage']="24";
$z[5]=Array("pagelist","",1745,1774);
$z[5][4]['listsize']="4";
$z[6]=Array("include","",1990,2034);
$z[6][4]['filename']="footer_92game.htm";

?>