<?php
$z[0]=Array("arcurl","",13,29);
$z[1]=Array("title","",62,77);
$z[2]=Array("senddate","\r\n                \$nowtime = time();\r\n                if(time() - @me < (3600*24)) @me = \"(New)\";\r\n                else @me = \"\";\r\n                ",124,317);
$z[2][4]['runphp']="yes";
$z[3]=Array("click","\r\n                if(@me>500) @me = \"(Hot)\";\r\n                else @me = \"\";\r\n                ",335,469);
$z[3][4]['runphp']="yes";

?>