<li>
		<h4><a title=[field:title/] href="[field:filename/]">[field:title/]</a></h4>
		<a href="[field:filename/]" class="box21_p">[field:description function='cn_substr(@me,150)'/]...</a>
		<p><span class="floatR"><a class="blue"  href="[field:filename/]">查阅全文...</a></span>作者：<span class="yellow">[field:writer /]</span>发表于：<span class="yellow">{dede:field name='pubdate' function='GetDateMk(@me)'/}</span>点击：<span class="yellow">[field:click/]</span>评论：<span class="yellow">[field:postnum/]</span></p>
	</li>