<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[2]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[4]=array(0,1,1,'5Lq65omN5oub6IGY');
$cfg_Cs[5]=array(0,1,1,'5paw6Ze76LWE6K6v');
$cfg_Cs[13]=array(0,1,1,'6aaW6aG1');
$cfg_Cs[14]=array(0,1,1,'57uP6JCl6IyD5Zu0');
$cfg_Cs[15]=array(0,1,1,'5oiQ5Yqf5qGI5YiX');
$cfg_Cs[16]=array(0,1,1,'5ZCI5L2c5LyZ5Ly0');
$cfg_Cs[17]=array(5,1,1,'6KGM5Lia6LWE6K6v');
$cfg_Cs[18]=array(5,1,1,'5YWs5Y+45paw6Ze7');
?>