<?php
$z[0]=Array("field","",310,329);
$z[0][4]['name']="title";
$z[1]=Array("global","",330,356);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",397,426);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",466,524);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",806,841);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n                      <li ><a href=\"[field:typeurl/]\" target=\"_self\">[field:typename/]</a></li>                     \r\n								 ",1162,1349);
$z[5][4]['reid']="2";
$z[5][4]['type']="son";
$z[5][4]['row']="5";
$z[6]=Array("include","",1423,1458);
$z[6][4]['filename']="left.htm";
$z[7]=Array("field","",1562,1591);
$z[7][4]['name']="position";
$z[8]=Array("field","",1598,1617);
$z[8][4]['name']="title";
$z[9]=Array("field","",1687,1708);
$z[9][4]['name']="content";
$z[10]=Array("include","",1809,1844);
$z[10][4]['filename']="foot.htm";

?>