<?php
$z[0]=Array("field","",308,327);
$z[0][4]['name']="title";
$z[1]=Array("global","",328,354);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",395,424);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",464,522);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",804,839);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n                      <li ><a href=\"[field:typeurl/]\" target=\"_self\">[field:typename/]</a></li>                     \r\n								 ",1198,1380);
$z[5][4]['type']="son";
$z[5][4]['typeid']="21";
$z[6]=Array("include","",1463,1498);
$z[6][4]['filename']="left.htm";
$z[7]=Array("field","",1602,1631);
$z[7][4]['name']="position";
$z[8]=Array("field","",1638,1657);
$z[8][4]['name']="title";
$z[9]=Array("list","\r\n		<li><span>[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]</span><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n         ",1734,1899);
$z[9][4]['pagesize']="15";
$z[10]=Array("pagelist","",1979,2057);
$z[10][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[10][4]['listsize']="5";
$z[11]=Array("include","",2135,2170);
$z[11][4]['filename']="foot.htm";

?>