<?php
$z[0]=Array("include","",0,37);
$z[0][4]['filename']="header.htm";
$z[1]=Array("arclist","\r\n              <div style=\"width:274px;float:left;border-bottom:1px dashed #cccccc;text-align:left;height:28px; line-height:28px;\"><img src=\"/templets/wuge/Images/newstitle.jpg\" align=\"absmiddle\">&nbsp;&nbsp;\r\n                <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_self\">[field:title/]</a>\r\n              </div>\r\n				",628,1039);
$z[1][4]['typeid']="18";
$z[1][4]['row']="6";
$z[1][4]['titlelen']="40";
$z[1][4]['orderby']="";
$z[2]=Array("arclist","\r\n              <div style=\"width:274px;float:left;border-bottom:1px dashed #cccccc;text-align:left;height:28px; line-height:28px;\"><img src=\"/templets/wuge/Images/newstitle.jpg\" align=\"absmiddle\">&nbsp;&nbsp;\r\n                <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target=\"_self\">[field:title/]</a>\r\n              </div>\r\n			  ",3430,3842);
$z[2][4]['typeid']="17";
$z[2][4]['row']="6";
$z[2][4]['titlelen']="40";
$z[2][4]['orderby']="";
$z[3]=Array("include","",4138,4175);
$z[3][4]['filename']="footer.htm";

?>