<?php
$z[0]=Array("include","",0,37);
$z[0][4]['filename']="header.htm";
$z[1]=Array("include","",163,203);
$z[1][4]['filename']="left_news.htm";
$z[2]=Array("field","",660,689);
$z[2][4]['name']="position";
$z[3]=Array("list","\r\n                        <div style=\"border-bottom:1px dashed #cccccc;width:730px;clear:both;float:left;height:25px;line-height:25px;\"><span style=\"float:left;color:#4bae5b;\">·<a href=\"[field:arcurl/]\">[field:title/]</a></span><span class=\"Black-bbb\">[field:pubdate function=\"MyDate('Y.m.d',@me)\"/]</span></div>\r\n                        ",1131,1507);
$z[3][4]['pagesize']="15";
$z[4]=Array("pagelist","",1616,1694);
$z[4][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[4][4]['listsize']="5";
$z[5]=Array("include","",2221,2258);
$z[5][4]['filename']="footer.htm";

?>