<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[2]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[3]=array(0,1,1,'5Lqn5Lia5Z+65Zyw');
$cfg_Cs[4]=array(0,1,1,'5Zut5p6X57u/5YyW');
$cfg_Cs[5]=array(0,1,1,'6Iqx5pyo56ef5pGG');
$cfg_Cs[11]=array(0,1,1,'5Lq65omN5oub6IGY');
$cfg_Cs[8]=array(0,1,1,'5L2T6aqM5Yac5Zy6');
$cfg_Cs[12]=array(0,1,1,'6KeC5YWJ6YeH5pGY');
$cfg_Cs[13]=array(0,1,1,'5bqt6Zmi57u/5YyW');
$cfg_Cs[14]=array(0,1,1,'5peF5ri45LyR6Zey');
$cfg_Cs[15]=array(3,1,1,'6Iqx5Y2J');
$cfg_Cs[16]=array(3,1,1,'6IuX5pyo');
$cfg_Cs[17]=array(3,1,1,'6bKc5p6c');
?>